# Generated by Django 3.1.5 on 2021-01-23 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Toll', '0002_auto_20210123_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_registration',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes'),
        ),
    ]
