# Generated by Django 3.1.5 on 2021-01-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Toll', '0004_customer_registration_activation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_registration',
            name='activation_Date',
            field=models.DateTimeField(null=True),
        ),
    ]
