# Generated by Django 3.1.5 on 2021-01-30 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Toll', '0005_auto_20210127_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ewallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionID', models.CharField(blank=True, editable=False, max_length=100, unique=True)),
                ('amount', models.IntegerField()),
                ('mode', models.CharField(max_length=20)),
                ('EmpId', models.IntegerField(default=None)),
                ('cust_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Toll.customer_registration')),
            ],
        ),
    ]
