# Generated by Django 3.1.5 on 2021-02-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Toll', '0007_auto_20210130_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ewallet',
            name='cust_id',
            field=models.IntegerField(),
        ),
    ]
