# Generated by Django 3.1.5 on 2021-02-22 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Toll', '0010_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.IntegerField()),
                ('Total_Amount', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='ewallet',
            name='transaction_Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
