# Generated by Django 3.1.5 on 2021-02-22 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Toll', '0011_auto_20210222_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalamount',
            name='transaction_Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
